config/routes.rb
Rails.application.routes.draw do
  get 'password_changes/edit'
  get 'password_changes/update'
  root 'top_pages#top'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',   to: 'users#new'
  resources :groups do
    member do
      get :members
      get :join
      delete :exit
      resources :posts, only: [:create, :destroy]
    end
  end
  resources :users
  resources :password_changes, only: [:new, :create, :edit, :update]
end

app/controllers/password_changes_controller.rb
class PasswordChangesController < ApplicationController
  before_action :require_user_logged_in
  def new
  end
  
  def create
    @user = User.find_by(email: params[:password_changes][:email])
    if @user == current_user
      redirect_to edit_password_change_path(current_user)
    else
      flash.now[:danger] = "メールアドレスが違います。"
      render 'new'
    end
  end
  
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(password_params)                     
      flash[:success] = "パスワードを変更しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private
  
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
    
end

app/helpers/password_changes_helper.rb
module PasswordChangesHelper
end

app/views/password_changes/edit.html.erb
<div class = "container">
  <div class="row">
    <div class="col-md-6 offset-md-3 login-form">
      <h2 class = "text-center">パスワードの変更</h2>
      <%= form_with(model: @user, url: password_change_path(params[:id]),
                  local: true) do |f| %>
        <%= render 'layouts/error_messages', object: f.object %>
        <%= f.label :password, "新しいパスワード" %>
        <%= f.password_field :password, class: 'form-control' %>
  
        <%= f.label :password_confirmation, "パスワード確認" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <div class = "login-btn">
        <%= f.submit "変更", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/password_changes/new.html.erb
<div class = "container">
  <div class="row">
    <div class="col-md-6 offset-md-3 login-form">
      <h2 class = "text-center">パスワードの変更</h2>
      
      <%= form_with(url: password_changes_path, scope: :password_changes, local: true) do |f| %>
        <%= f.label :eamil, "メールアドレス" %>
        <%= f.email_field :email, class: 'form-control' %>
        <div class = "login-btn">
        <%= f.submit "送信", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/password_changes/update.html.erb
<h1>PasswordChanges#update</h1>
<p>Find me in app/views/password_changes/update.html.erb</p>