config/routes.rb
Rails.application.routes.draw do
  get 'password_changes/edit'
  get 'password_changes/update'
  root 'top_pages#top'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',   to: 'users#new'
  resources :groups do
    member do
      get :members
      get :join
      delete :exit
      resources :posts, only: [:create, :destroy]
    end
  end
  resources :users
  resources :password_changes, only: [:new, :create, :edit, :update]
end

app/models/group.rb
class Group < ApplicationRecord
  validates :learning, presence: true
  validates :limit, presence: true
  validates :content, presence: true, length: {maximum: 200}
  belongs_to :user
  has_many :members
  has_many :posts ,dependent: :destroy
  has_many :member, through: :members, source: :user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
   before_action :require_user_logged_in
   before_action :members?, only: [:members, :exit]
   before_action :members_over?, only: [:join]
   after_action :group_delete, only: [:exit]
   
  
  def index
    @groups = Group.order(id: :desc).page(params[:page]).per(6)
    #@groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      current_user.join(@group)
      redirect_to members_group_path(@group)
    else
      flash.now[:danger] = "全ての項目に入力をしてください。"
      render new_group_path
    end
  end

  def join
    @group = Group.find(params[:id])
    current_user.join(@group)
    redirect_to members_group_path(@group)
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end
  
  def members
    @group = Group.find(params[:id])
    @post = current_user.posts.build
    @posts = @group.posts 
  end
  
  def exit
    @group = Group.find(params[:id])
    current_user.exit(@group)
    redirect_to groups_path
  end
  
  
  private
  
  def group_params
    params.require(:group).permit(:limit, :learning, :content)
  end
  
  def group_delete
    @group = Group.find(params[:id])
    if @group.member.count == 0
      @group.destroy
    end
  end
  
  def members?
    unless current_user.members.find_by(group_id: params[:id])
      redirect_to groups_path
    end
  end
  
  def members_over?
      @group = Group.find(params[:id])
      if @group.members.count >= @group.limit
        flash[:warning]="満員のため参加できません。"
        redirect_to group_path(@group)
      end
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group_card.html.erb
<div class="row">
  <% groups.each do |group| %>
  <div class="col-sm-6 mt-3">
    <%= render "layouts/card", group: group %>
  </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class = "group-lists">
    <div class = "container">
        <h2>
            グループ一覧
        </h2>
        <%= render 'group_card', groups: @groups %>
        <%= paginate @groups %>
        <div class = "create_group_btn">
            <%= link_to "グループを作成", new_group_path, class: "btn btn-lg btn-primary" %>
        </div>
    </div>
</div>

app/views/groups/members.html.erb
<div class = "chatroom">
  <div class = "container">
    <%= link_to "Chat room", group_path(@group), class: "room-logo" %>
    <div class = "row">
      <div class = "col-md-8 order-md-1 scroll over-wrap" id='posts'>
        <%= render @posts %>
      </div>
      <div class="col-md-4 order-md-0">
        <%= current_user.name %>
        <%= form_with(model: @post, local: true) do |f| %>
        <%= render 'layouts/error_messages', object: f.object %>
          <div class="form-group">
            <%= text_field_tag 'post[group_id]', "#{@group.id}", type: "hidden" %>
            <%= f.text_area :message, class: 'form-control', rows: 3, data: { behavior: 'group_speaker' } %>
          </div>
          <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
        <% end %>
         <%= render 'layouts/members_name', group: @group %>
        <% if @group.members.count == 1 %>
          あなたが退出するとこのグループは自動的に削除されます。
          <%= button_to "退出してグループを削除", exit_group_path(@group), method: :delete , class: "btn btn-outline-primary" %>
        <% else %>
          <%= button_to "退出", exit_group_path(@group), method: :delete , class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class = "create_group">
  <div class = "container">
    <h2>グループ作成</h2>
    <%= form_with(model: @group, local: true) do |f| %>
    <%= render 'layouts/error_messages', object: f.object %>
      <span>作成者</span>
      <p><%= @group.user.name %></p>

      <%= f.label :learning, "学習言語" %>
      <%= f.select :learning, [["HTML/CSS","HTML/CSS"],["JavaScript","JavaScript"],["Ruby/Ruby on Rails","Ruby/Ruby on Rails"],
      ["PHP/Laravel","PHP/Laravel"],["Python/Django","Python/Django"],["Java","Java"]], {include_blank: "言語を選択してください"}, {class: 'custom-select'} %>
      
      <%= f.label :limit, "参加できる人数" %>
      <%= f.select :limit, [[2,2],[3,3],[4,4],[5,5]], {include_blank: "人数を選択してください"}, {class: 'custom-select'} %>

      <%= f.label :content, "メッセージ" %>
      <%= f.text_area :content, class: 'form-control' %>
      <div class = "login-btn">
        <%= f.submit "登録", class: "btn btn-success" %>
      </div>
      
      <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class = "show_group">
  <div class = "container">
    <h2>グループ詳細</h2>
      <%= render 'layouts/group_info', group: @group %>
      <%= render 'layouts/members_name', group: @group %>
      <h5>メッセージ</h5>
      <div class = "message over-wrap">
        <%= @group.content %>
      </div>
      <% if current_user.group.find_by(id: params[:id]) == @group %>
        <%= link_to "ルームに移動", members_group_path(@group), class: "btn btn-primary" %>
      <% elsif @group.members.count < @group.limit%>
        <%= link_to "グループに参加", join_group_path(@group), class: "btn btn-primary" %>
      <% else %>
        <a href="#" class="btn btn-secondary disabled" tabindex="-1" role="button" aria-disabled="true">満員</a>
      <% end %>
  </div>
</div>