config/routes.rb
Rails.application.routes.draw do
  get 'password_changes/edit'
  get 'password_changes/update'
  root 'top_pages#top'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',   to: 'users#new'
  resources :groups do
    member do
      get :members
      get :join
      delete :exit
      resources :posts, only: [:create, :destroy]
    end
  end
  resources :users
  resources :password_changes, only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format:{with:VALID_EMAIL_REGEX},
            uniqueness: true
  validates :content, length: {maximum: 200}
  has_secure_password
  
  has_many :groups
  has_many :members
  has_many :posts
  has_many :group ,through: :members, source: :group
  attr_accessor :remember_token
  
  #渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    #Userのremember_token属性をここで定義。
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def join(will_join_group)
    unless self.members.find_by(group_id: will_join_group)
      self.members.find_or_create_by(group_id: will_join_group.id)
    end
  end
  
  def exit(join_group)
    grp = self.members.find_by(group_id: join_group.id)
    grp.destroy if grp
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update]
  def index
    #@users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    if logged_in?
      redirect_to groups_path
    else
      @user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)    
    if @user.save
      log_in(@user)
      flash[:success] = "登録に成功しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "登録に失敗しました。"
      render :new
    end
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_edit_params)
      flash[:success] = "プロフィールの変更を保存しました。"
      redirect_to @user
    else
      flash.now[:danger] = "保存に失敗しました。"
      render :edit
    end
  end
  
  # def delete
  # end


  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
  
  def user_edit_params
    params.require(:user).permit(:name, :content)
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class = "user-edit">
  <div class = "container">
    <div class="row">
      <div class="col-md-12">
        <h2>プロフィール編集</h2>
        
        
        <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', object: f.object %>
          <%= f.label :name, "名前" %>
          <%= f.text_field :name, class: 'form-control' %>
    
          <%= f.label :content, "プロフィール文" %>
          <%= f.text_area :content, class: 'form-control' %>
          
          <div class = "save-btn">
          <%= f.submit "保存", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class = "container">
  <div class="row">
    <div class="col-md-6 offset-md-3 login-form">
      <h2 class = "text-center">新規登録</h2>
      
      <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', object: f.object %>
        <%= f.label :name, "氏名" %>
        <%= f.text_field :name, class: 'form-control' %>
  
        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, class: 'form-control' %>
        
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, class: 'form-control' %>
  
        <%= f.label :password_confirmation, "パスワード確認" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <div class = "login-btn">
        <%= f.submit "登録", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "user_profile">
  <div class = "container">
    <h2>プロフィール</h2>
    <!--画像挿入欄-->
    <p><%= @user.name %></p>
    <% if current_user? %>
      <div class = "user_menu">
        <div class = "user_edit_btn">
          <%= link_to "編集", edit_user_path(@user), class: 'btn btn-md btn-primary'%>
        </div>
      </div>
    <% end %>
    <% unless @user.content.blank? %>
    <div class = "message over-wrap">
      <%= @user.content %>
    </div>
    <% end %>
    <h5>現在参加中のグループ</h5>
    <div class = "row">
      <% if current_user == @user %>
      
        <% if @user.group.empty? %>
          <div class = "col-md-6">
            <%= render "layouts/not_join_group" %>
          </div>
        <% else %>
          <div class = "col-md-6">
            <%= render "layouts/card", group: @user.group.first %>
          </div>
        <% end %>
          <div class = "create_group_btn col-md-6">
            <%= link_to "グループ作成", new_group_path, class: 'btn btn-md btn-primary create-btn' %>
          </div>
          
      <% else %>
      
        <% if @user.group.empty? %>
          <div class = "col-md-6 offset-md-3">
            <%= render "layouts/not_join_group" %>
          </div>
        <% else %>
          <div class = "col-md-6 offset-md-3">
            <%= render "layouts/card", group: @user.group.first %>
          </div>
        <% end %>
        
      <% end %>
    </div>
  </div>
</div>