config/routes.rb
Rails.application.routes.draw do
  get 'password_changes/edit'
  get 'password_changes/update'
  root 'top_pages#top'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',   to: 'users#new'
  resources :groups do
    member do
      get :members
      get :join
      delete :exit
      resources :posts, only: [:create, :destroy]
    end
  end
  resources :users
  resources :password_changes, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :learning, presence: true
  validates :limit, presence: true
  validates :content, presence: true, length: {maximum: 200}
  belongs_to :user
  has_many :members
  has_many :posts ,dependent: :destroy
  has_many :member, through: :members, source: :user
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  validates :message, presence: true, length: {maximum: 200}
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format:{with:VALID_EMAIL_REGEX},
            uniqueness: true
  validates :content, length: {maximum: 200}
  has_secure_password
  
  has_many :groups
  has_many :members
  has_many :posts
  has_many :group ,through: :members, source: :group
  attr_accessor :remember_token
  
  #渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    #Userのremember_token属性をここで定義。
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def join(will_join_group)
    unless self.members.find_by(group_id: will_join_group)
      self.members.find_or_create_by(group_id: will_join_group.id)
    end
  end
  
  def exit(join_group)
    grp = self.members.find_by(group_id: join_group.id)
    grp.destroy if grp
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
   before_action :require_user_logged_in
   before_action :members?, only: [:members, :exit]
   before_action :members_over?, only: [:join]
   after_action :group_delete, only: [:exit]
   
  
  def index
    @groups = Group.order(id: :desc).page(params[:page]).per(6)
    #@groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      current_user.join(@group)
      redirect_to members_group_path(@group)
    else
      flash.now[:danger] = "全ての項目に入力をしてください。"
      render new_group_path
    end
  end

  def join
    @group = Group.find(params[:id])
    current_user.join(@group)
    redirect_to members_group_path(@group)
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end
  
  def members
    @group = Group.find(params[:id])
    @post = current_user.posts.build
    @posts = @group.posts 
  end
  
  def exit
    @group = Group.find(params[:id])
    current_user.exit(@group)
    redirect_to groups_path
  end
  
  
  private
  
  def group_params
    params.require(:group).permit(:limit, :learning, :content)
  end
  
  def group_delete
    @group = Group.find(params[:id])
    if @group.member.count == 0
      @group.destroy
    end
  end
  
  def members?
    unless current_user.members.find_by(group_id: params[:id])
      redirect_to groups_path
    end
  end
  
  def members_over?
      @group = Group.find(params[:id])
      if @group.members.count >= @group.limit
        flash[:warning]="満員のため参加できません。"
        redirect_to group_path(@group)
      end
  end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
   @group = current_user.group.find_by(id: params[:id])
   @post = current_user.posts.build(post_params)
   if @post.save
    redirect_to members_group_path(@group)
   else
     @posts = @group.posts
     render 'groups/members'
   end
  end
  
  def delete
    
  end
  
  private
  
  def post_params
    params.require(:post).permit(:message, :group_id)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      remember(@user)
      redirect_to groups_path
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render 'new'
    end
  end

  def destroy
    forget(current_user)
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update]
  def index
    #@users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    if logged_in?
      redirect_to groups_path
    else
      @user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)    
    if @user.save
      log_in(@user)
      flash[:success] = "登録に成功しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "登録に失敗しました。"
      render :new
    end
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_edit_params)
      flash[:success] = "プロフィールの変更を保存しました。"
      redirect_to @user
    else
      flash.now[:danger] = "保存に失敗しました。"
      render :edit
    end
  end
  
  # def delete
  # end


  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
  
  def user_edit_params
    params.require(:user).permit(:name, :content)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/password_changes_helper.rb
module PasswordChangesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
  #ユーザー詳細ページの編集機能を表示するかしないかに利用
  def current_user?
    current_user == User.find_by(id: params[:id])
  end
  
  def group_member?
    current_user.members.find_by(group_id: params[:id])
  end
  
   # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
    
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_card.html.erb
<div class="card">
  <div class="card-body">
    <%= render 'layouts/group_info', group: group %>
      <div class = "row chunk">
        <div class = "col-6">
          <span>参加人数</span>
          <span><%= group.members.count %>人/<%= group.limit %>人</span>
        </div>
        <div class = "col-6 group-detail">
          <%= link_to "グループ詳細", group_path(group), class: "btn btn-primary" %>
        </div>
      </div>
  </div>
</div>

app/views/layouts/_dropdown_menu.html.erb
<div class="dropdown ml-auto">
  <a class="btn btn-outline-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= current_user.name %>
  </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
      <%= link_to "グループ一覧",groups_path, class: "btn btn-outline-primary dropdown-item" %>
      <%= link_to "プロフィール",user_path(current_user), class: "btn btn-outline-primary dropdown-item" %>
      <%= link_to "パスワードの変更", new_password_change_path, class: 'btn btn-outline-primary dropdown-item' %>
      <%= button_to "ログアウト", logout_path, method: :delete, class: "btn btn-outline-primary dropdown-item"  %>
    </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-warning">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  
</footer>

app/views/layouts/_group_info.html.erb
<div class = "chunk">
  <span><%= group.created_at.strftime("%m/%d %H:%M")%></span>
</div>
<div class = "chunk">
  <span class = "card-subtitle">作成者：</span>
  <%=link_to group.user.name, user_path(group.user)%>
</div>
<div class = "chunk">
  <span class = "card-subtitle">学習言語：</span>
  <span><%= group.learning %></span>
</div>

app/views/layouts/_header.html.erb
<header>
  <% if logged_in? %>
    <%= render "layouts/nav_login" %>
  <% else %>
   <%= render "layouts/nav_toppage" %>
  <% end %>
</header>

app/views/layouts/_members_name.html.erb
<div class = "chunk">
  <span class = "card-subtitle">参加者：</span>
  <% group.member.each do |user| %>
    <%= link_to "#{user.name}", user_path(user), class: "mr-2" %>
  <% end %>
</div>

app/views/layouts/_nav_chatroom.html.erb
<nav class = "navbar navbar-expand headnav">
    <%= render 'layouts/dropdown_menu' %>
</nav>

app/views/layouts/_nav_login.html.erb
<nav class="navbar navbar-expand-sm headnav">
  <a href="/" class="navbar-brand">Kakehashi</a>
    <%= render 'layouts/dropdown_menu' %>
</nav>

app/views/layouts/_nav_toppage.html.erb
<nav class = "navbar navbar-expand headnav">
    <a href="/" class="navbar-brand">Kakehashi</a>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item mr-4"><%= link_to "新規登録", signup_path, class: "btn btn-outline-primary"%></li> 
        <li class="nav-item mr-1"><%= link_to "ログイン", login_path, class: "btn btn-outline-primary"%></li>
    </ul>
</nav>

app/views/layouts/_not_join_group.html.erb
<div class="card">
  <div class="card-body">
      <h4 class ="card-title">現在グループに<br>参加していません。</h4>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>KakehashiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'dataturbolinkstrack': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'dataturbolinkstrack': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages'%>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>